### ISSUE TITLE
faulty regex in magic.mgc

### ISSUE THREAD

**Issue by DaGaMs** [mscdex/mmmagic#102] opened 2017-03-16 14:27 UTC
There's a bug in one of the REGEXes:

    regex error 11 for `\t\\*|([0-9]+[MIDNSHPX=])+)\t', (unbalanced () at offset 24    )

This issue has been noted before: 

- https://github.com/Alexpux/MSYS2-packages/commit/6326da8a38fff8297829e15571190de91391d0cc
- https://bugs.gw.com/view.php?id=558

How can we fix the magic file? I'd do it if I knew how to.

**Comment by mscdex** [comment] 2017-09-12 23:23
Please try the master branch, I have merged in libmagic 5.32 now.

This is also a duplicate of https://github.com/mscdex/mmmagic/issues/114.

**Closed by mscdex** 2017-09-12 23:23 UTC
